id: A4AFA548B
title: A Brief Prayer for Summoning Prosperity
type: translation
pechas:
- I3C3F6FDB
- IAAFDD4C9
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:04:33.675819
  last_modified_at: 2023-01-04 13:04:33.675822
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I3C3F6FDB/D186: '6228'
  IAAFDD4C9/14C2: '6228'
